name: Generate build

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: frontend/build

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Get build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-files
