name: Test worklow
on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main
      
jobs:
  test:
      runs-on: ubutun-latest
      env:
        NODE_ENV: test
      steps:
        - name: Get the code
          uses: actions/checkout@v3.3.0
        - name: Intall NodeJs
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install dependencies
          run: npm ci
          working-directory: backend
        - name: Docker compose
          run: |
              docker-compose up -d backend db_test 
              docker ps
        - name: Sleep for 10 seconds
          uses: jakejarvis/wait-action@master
          with:
             time: "10s"
        - name: Run migrations
          run: docker-compose exec -T backend npx sequelize db:migrate --env test
        - name: Run tests
          run: docker-compose exec -T backend npx jest
        
          
